version: '3'

services:
  books-reviewer:
    environment:
      VERSION: $(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}
    image: ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:${VERSION}
    ports:
      - 8080:8080
    secrets:
      - dockerhub_username
      - dockerhub_password

secrets:
  dockerhub_username:
    external: true
  dockerhub_password:
    external: true
