
services:
  
  books-reviewer:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:${VERSION}
    ports:
      - 8080:8080
    environment:
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}
    secrets:
      - dockerhub_username
      - dockerhub_password
secrets:
  dockerhub_username:
    external: true
  dockerhub_password:
    external: true

env:
  VERSION: $(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
