version: '3'

services:
  books-reviewer:
    environment:
      DOCKERHUB_USERNAME: ${DOCKERHUB_USERNAME}
      DOCKERHUB_TOKEN: ${DOCKERHUB_TOKEN}
    image: ${{ secrets.DOCKERHUB_USERNAME }}/books-reviewer:0.2.0-SNAPSHOT # Write it literally due to env problems
    ports:
      - 8080:8080
    secrets:
      - dockerhub_username
      - dockerhub_password

secrets:
  dockerhub_username:
    external: true
  dockerhub_password:
    external: true
